sonar.projectKey=YOUR_PROJECT_KEY
sonar.organization=YOUR_ORGANIZATION

sonar.sources=user-service,product-service,order-service

sonar.exclusions=**/migrations/**,**/__pycache__/**

sonar.python.version=3.12

sonar.sourceEncoding=UTF-8