sonar.projectKey=navaneethsankar07_ecommerce-microservices-practice
sonar.organization=navaneethsankar07

sonar.sources=user-service,product-service,order-service

sonar.exclusions=**/migrations/**,**/__pycache__/**

sonar.python.version=3.12

sonar.python.coverage.reportPaths=user-coverage/coverage.xml,product-coverage/coverage.xml,order-coverage/coverage.xml

sonar.sourceEncoding=UTF-8