apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
      - name: product-service

        image: navaneethsankar7/product-service:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SECRET_KEY

        - name: DB_NAME
          value: product_db

        - name: DB_USER
          value: postgres

        - name: DB_PASSWORD
          value: postgres

        - name: DB_HOST
          value: product-db

        - name: DB_PORT
          value: "5432"