name: Microservices CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-and-analyze:

    runs-on: ubuntu-latest

    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install User Service Dependencies
        working-directory: user-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Install Product Service Dependencies
        working-directory: product-service
        run: |
          pip install -r requirements.txt


      - name: Install Order Service Dependencies
        working-directory: order-service
        run: |
          pip install -r requirements.txt

      - name: Test User Service
        working-directory: user-service
        run: |
          python manage.py test


      - name: Test Product Service
        working-directory: product-service
        run: |
          python manage.py test

      - name: Test Order Service
        working-directory: order-service
        run: |
          python manage.py test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}